[package]
name = "safari"
version = "0.9.0"
edition = "2021"

description = "safari checkpoint"
homepage = "https://github.com/lhpqaq/safari"
repository = "https://github.com/lhpqaq/safari"
license = "MIT"

[dependencies]
regex = "1.11.0"
serde_json = "1.0.129"

